version: '3.8'
services:
  frenchie-store-host:
    build:
      context: ./host-app
    container_name: frenchie-store-host
    stdin_open: true
    networks:
      - uFE
  mf-products:
      build:
        context: ./mf-products
      container_name: mf-products
      stdin_open: true
      networks:
      - uFE
  mf-cart:
    build:
      context: ./mf-cart
    container_name: mf-cart
    stdin_open: true
    networks:
      - uFE
  backend:
    build:
      context: './backend'
    container_name: frenchie-store-backend
    networks:
      - uFE
  router:
    build:
      dockerfile: dockerfile
      context: ./router
    ports:
      - "3004:80"
    networks:
      - uFE
  
networks:
    uFE:
        external: true
        name: uFE