version: '2.0'
services:
  frenchie-store-host:
    build:
      context: ./host-app
    ports:
      - "3000:3000"
    container_name: frenchie-store-host
    stdin_open: true
    networks:
      - uFE
  mf-products:
      build:
        context: ./mf-products
      ports:
        - "3001:80"
      container_name: mf-products
      stdin_open: true
    networks:
      - uFE
  mf-cart:
    build:
      context: ./mf-cart
    ports:
      - "3002:80"
    container_name: mf-cart
    stdin_open: true
    networks:
      - uFE
  backend:
    build:
      context: './backend'
    ports:
      - "3003:3003"
    container_name: frenchie-store-backend
    networks:
      - uFE
  router:
    build:
      dockerfile: dockerfile
      context: ./router
    ports:
      - "3004:80"
    networks:
      - uFE
  
networks:
    uFE:
        external: true
        name: uFE